### ISSUE TITLE
Shoot a loop screen upload problems

### ISSUE THREAD

**Issue by batuhan** [barbar/proco#161]
Except for my own device (iPhone 6 with the app installed in development mode), other devices fail to upload loop to Firebase. We also get an error related to the pollyfill we use in the console. 

I think the best way to solve this would be switching the upload process to the native side. We can use the code from `react-native-firestack` (See [here](https://github.com/fullstackreact/react-native-firestack/blob/master/ios/Firestack/FirestackStorage.m)) Just to be clear, I'm not saying we should use this module, just copy the code into our own repo.

The problem here is we don't share user sessions between the native side and the JavaScript side. We can authenticate with the Facebook token in the native side too.

**Comment by loetjvr** [comment]
Seems like Firebase might have made some fixes from their side and the currently solution is working now. We will leave it for a while to see if it holds true

**Comment by sevims** [comment]
@loetjvr does it still work? batuhan checked and he said the upload is currently messed up. He proposed a workaround using google cloud storage directly via https://cloud.google.com/storage/docs/json_api/v1/how-tos/resumable-upload 

What do you think ?

**Comment by loetjvr** [comment]
Seems like RNFetchBlob pollyfills is causing the issue
