### ISSUE TITLE
Flow problems

### ISSUE THREAD

**Issue by batuhan** [barbar/proco#174]
- [ ]  Type your university modal height
- [ ]  Back button doesn’t work if the e-mail is not correct
- [ ]  Mail is not sending 
- [ ]  Add a send button and make the modal smaller (also the modal should go up as the keyboard comes)
- [x]  Pool background colour should change
- [ ]  Add redirection back to app in to the network - verification
- [ ]  Location not authorised modal is not appearing 
- [x]  Radar video gets stuck at 1 pm mark on every turn
- [ ]  Change the loading icon on the verification page to mail icon
- [ ]  We can’t come to the camera after the initial shoot
- [ ]  Update your question background
- [ ]  Make question bubble single line
- [ ]  Find a way to make bubble bigger without multiline
- [ ]  Pool check in intervals 
- [ ]  Return to main screen after shooting a new profile loop.
- [ ]  Application start animation will be large flashing Proco logo.  (during connection to firebase,etc)
- [ ]  Last pool item must swipe to `PoolInProgress` component
- [ ]  Shoot a new profile loop defaults to camera shot screen

**Comment by sevims** [comment]
Merged into #159. Closing this one.
